### PR TITLE
Float branch lengths and utility functions

### PR DESCRIPTION
**Pull request by lmaurits**
Here is my first attempt at implementing support for non-string branch lengths.  The module contains two functions, branch_parser and branch_formatter.  By default, these are:

`branch_parser = lambda x: float(x or 0)
branch_formatter = str`

but the user can override them by assigning their own functions to these names if necessary (I think these are quite conservative defaults - the parser should be able to handle the vast majority of trees in the wild.  If anybody knows of exceptions please let me know).  The formatter is necessary in case a parsed length is changed before the tree is dumped.  Faithful round-tripping continues to be supported.

Implementing this pluggable functionality with standalone functions feels a bit weird to me, but I didn't know how else to proceed - if they are methods of Node, subclassing Node to change them is no good, as parse_node is hard-coded to use the vanilla Node class.  Directly overriding class methods feels even weirder than doing so with standalone functions.  If there is some standard Pythonic way to do this, feel free to implement it.

Also included are a few utility functions, the ones of substance are pruning (removing a specified set of leaves, or removing all leaves except a specified set), removing redundant nodes (does this process have a well-known name?) and resolving polytomies.  All utility functions are < 10 LOC and take 2 parameters or less, so I don't feel like they compromise the minimalist spirit of the library, but I am very open to discussion on what does and does not get included.

### CODE REVIEW

**Comment by lmaurits** [comment]
Regarding what to call "remove_redundant_nodes": DendroPy calls this "supress_unifurcations".  Maybe we could use "remove_unifurcations"?

**Comment by xrotwang** [comment]
I'm not used to DendroPy and pyhlogeny in general, so "unifurcation" doesn't sound very common to me. But it still has more specific meaning than "redundant_nodes", I guess. So I'd vote for "remove_unifurcations".

**Comment by lmaurits** [comment]
I had not heard of "unifurcation" before either, but I have heard "multifurcation" often.  I think people usually use it as an alternative to "polytomy", but that might not be strictly accurate (since I would think bifurcation is a special case of multifurcation).

**Comment by xrotwang** [comment]
Plugging in functionality by monkey patching functions in an imported module feels a bit weird to me. I'd rather have these functions passed into `Node.__init__` (and probably also to all the higher-level parsing functions). I'm merging anyway, and we can discuss this question in a new ticket.

**Comment by lmaurits** [comment]
Okay, no problem.  I originally planned to do it that way, but it ended up feeling a bit ugly because the functions had to be passed down through so many calls to get from functions like read() to Node.**init**.  But I'm happy to discuss this in detail in a new issue.

**Pull request merged**
