### PR TITLE
Fix bug from iteration behaviour

### LINKED ISSUE #27: `remove_redundant_nodes` leaves redundant nodes
When there are multiple leaves each with a singleton parent, `remove_redundant_nodes` skips some.

```
>>> import newick newick
>>> tree = newick.loads("((aiw),((aas,(kbt)),((abg),abf)))")[0]
>>> tree.remove_redundant_nodes()
>>> tree.newick
'(((aas,(kbt)),((abg),abf)),aiw:0.0)'
```

This should give

```
'(((aas,kbt),(abg,abf)),aiw:0.0)'
```

or something equivalent instead.

### PR DESCRIPTION
**Pull request by Anaphory**
This fixes #27 and adds a test for the buggy behaviour observed there.

### CODE REVIEW

**Comment by xrotwang** [comment]
I think I like these changes, in particular with the added tests :)
This will introduce a breaking change to the API, though, so would have to go into version 1.0.0.

**Comment by xrotwang** [comment]
@lmaurits Could you test whether this would break any of the newick uses in beastling?

**Comment by xrotwang** [comment]
@Anaphory `length_formatter` is only ever used in `Node.newick`, so maybe it should better be an optional argument of this method, rather than of `Node.__init__`? This would also provide a clearer separation of tree construction from serialization.

I'm still a bit unsure about `remove_redundant_nodes`. One could argue that passing `preserve_lengths=True` implicitly means the caller knows node lengths to be numbers, but maybe that should be made more transparent? `+=` will also work on strings but presumably not in the intended way.

**Comment by Anaphory** [comment]
Moving `length_formatter` to `Node.newick` (which regularly confuses me for being a property – not a method – anyway, so that's an API change I would welcome, but which would break some workflows) sounds very good!

Concatenating strings as a means of “preserving lengths” does not sound convincing, indeed.
Making that clear in the docstring will be the minimum necessary, maybe there is a better solution.

**Comment by xrotwang** [comment]
Yeah, make this 1.0.0.
Am 13.01.2017 16:11 schrieb "Gereon Kaiping" <notifications@github.com>:

**Comment by Anaphory** [comment]
I had this issue again. I will hopefully make this mergeable with `master` at some point reasonably soon, but I have too many other things to deal with in the near future.

**Comment by xrotwang** [comment]
I added what seem to be the tests for the desired behaviour to HEAD (https://github.com/dlce-eva/python-newick/commit/4ec07e0da1ea14c5d6e65c3d01c94674f68bf5be) so I'd consider this implemented/dealt with.

**Pull request closed without merging**
